# Generated by Django 2.2.3 on 2019-07-21 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='psuedonym',
            new_name='pseudonym',
        ),
    ]
